// <auto-generated />
namespace SportLigue.MainApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IndexReconfigure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IndexReconfigure));
        
        string IMigrationMetadata.Id
        {
            get { return "202001201307200_IndexReconfigure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
